import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    labelApproval: "approval",
    labelQuestion: "question",
    labelImages: "images",
    labelHtml: "html",
    labelChart: "chart",
    labelRefresh: "refresh",
    labelSubagent: "subagent",
    labelDelegation: "delegation",
    labelExaSearch: "exa",
    labelMemory: "memory",
    
    argApprovalRequest: "Approval Request",
    argUserQuestion: "User Question",
    argImages: "images",
    argChart: "Chart",
    argHtmlDoc: "HTML document",
    argUiRefresh: "UI refresh",
    
    resWaiting: "waiting...",
    resRendered: "rendered",
    resShared: "shared",
    resRefreshed: "refreshed",
    resCompleted: "completed",
    resExaResults: "results",
    resExaResult: "result",
    resMemories: "memories",
    resMemory: "memory",
    resStored: "stored",
    resForgotten: "forgotten",
    
    bodySubagentConsole: "Subagent Console",
    bodyViewLiveConsole: "View",
    bodySubagentView: "View",
    bodyWorkspaceRefreshed: "Workspace sections refreshed: ",
    bodyDelegationTo: "Delegation to",
    bodySynthesizedOutput: "Synthesized Output",
    bodyShowMore: "Show {n} more",
    bodyNoResults: "No results found",
    bodyNoMemories: "No relevant memories found",
    bodyMemoriesRecalled: "memories recalled",
    labelDecompose: "planning",
    resDecomposed: "plan generated",
    bodyObjective: "Objective",
    bodyTasksPlanned: "Tasks Planned",
    bodyDependsOn: "depends on",
    bodyEstimatedSteps: "Est. Steps",
    
    labelWebFetch: "web_fetch",
    bodyWebFetchTitle: "Web Content",
    bodyWebFetchSource: "Source",
    bodyWebFetchCached: "Cached",
    bodyWebFetchTruncated: "Truncated",
    bodyWebFetchMethod: "Method",
    bodyWebFetchTime: "Duration",
    bodyWebFetchOriginalSize: "Original size",
    bodyWebFetchExtractedSize: "Extracted size",
    bodyWebFetchShowContent: "Show Page Content",
    bodyWebFetchHideContent: "Hide Page Content",
    labelManageCustomTools: "custom tools",
  },
  es: {
    labelApproval: "aprobación",
    labelQuestion: "pregunta",
    labelImages: "imágenes",
    labelHtml: "html",
    labelChart: "gráfico",
    labelRefresh: "refrescar",
    labelSubagent: "subagente",
    labelDelegation: "delegación",
    labelExaSearch: "exa",
    labelMemory: "memoria",
    
    argApprovalRequest: "Petición de aprobación",
    argUserQuestion: "Pregunta al usuario",
    argImages: "imágenes",
    argChart: "Gráfico",
    argHtmlDoc: "documento HTML",
    argUiRefresh: "refresco de UI",
    
    resWaiting: "esperando...",
    resRendered: "renderizado",
    resShared: "compartido",
    resRefreshed: "refrescado",
    resCompleted: "completado",
    resExaResults: "resultados",
    resExaResult: "resultado",
    resMemories: "memorias",
    resMemory: "memoria",
    resStored: "guardado",
    resForgotten: "eliminado",
    
    bodySubagentConsole: "Subagente Consola",
    bodyViewLiveConsole: "Ver",
    bodySubagentView: "Ver",
    bodyWorkspaceRefreshed: "Secciones del espacio de trabajo refrescadas: ",
    bodyDelegationTo: "Delegación a",
    bodySynthesizedOutput: "Output sintetizado",
    bodyShowMore: "Mostrar {n} más",
    bodyNoResults: "No se encontraron resultados",
    bodyNoMemories: "No se encontraron memorias relevantes",
    bodyMemoriesRecalled: "memorias recordadas",
    labelDecompose: "planificación",
    resDecomposed: "plan generado",
    bodyObjective: "Objetivo",
    bodyTasksPlanned: "Tareas Planificadas",
    bodyDependsOn: "depende de",
    bodyEstimatedSteps: "Pasos Est.",
    
    labelWebFetch: "web_fetch",
    bodyWebFetchTitle: "Contenido Web",
    bodyWebFetchSource: "Fuente",
    bodyWebFetchCached: "En Caché",
    bodyWebFetchTruncated: "Truncado",
    bodyWebFetchMethod: "Método",
    bodyWebFetchTime: "Duración",
    bodyWebFetchOriginalSize: "Tamaño original",
    bodyWebFetchExtractedSize: "Tamaño extraído",
    bodyWebFetchShowContent: "Ver Contenido de la Página",
    bodyWebFetchHideContent: "Ocultar Contenido de la Página",
    labelManageCustomTools: "herramientas personalizadas",
  },
};
