import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    placeholderSteer: "Steer agent... (Enter to steer, Alt+Enter to enqueue follow-up)",
    placeholderSend: "Send a message... (Enter to send, Shift+Enter for new line)",
    placeholderRunnerActive: "Task runner is active. Pause execution to send messages manually.",
    btnSend: "Send",
    btnStop: "Stop",
    btnSteer: "Steer",
    btnFollowUp: "Follow-up",
    attachFiles: "Attach files",
    searchSkills: "Search skills...",
    noSkills: "No active skills in this session",
    fullAccess: "Autonomous",
    standard: "Standard",
    readOnly: "Read-Only",
    recentModels: "Recent",
    connectProviders: "Connect more providers",
    mentionHeader: "Mention",
    skillsHeader: "Skills",
    toolsHeader: "Tools",
    skillsLabel: "Skills",
    toolsLabel: "Tools",
    ariaSend: "Send message",
    ariaStop: "Stop generation",
  },
  es: {
    placeholderSteer: "Guiar agente... (Enter para guiar, Alt+Enter para encolar follow-up)",
    placeholderSend: "Enviar mensaje... (Enter para enviar, Shift+Enter para nueva línea)",
    placeholderRunnerActive: "El gestor de tareas está activo. Pausá la ejecución para enviar mensajes manualmente.",
    btnSend: "Enviar",
    btnStop: "Detener",
    btnSteer: "Guiar",
    btnFollowUp: "Follow-up",
    attachFiles: "Adjuntar archivos",
    searchSkills: "Buscar skills...",
    noSkills: "No hay skills activas en esta sesión",
    fullAccess: "Autónomo",
    standard: "Estándar",
    readOnly: "Solo Lectura",
    recentModels: "Recientes",
    connectProviders: "Conectar más proveedores",
    mentionHeader: "Mención",
    skillsHeader: "Skills",
    toolsHeader: "Herramientas",
    skillsLabel: "Skills",
    toolsLabel: "Herramientas",
    ariaSend: "Enviar mensaje",
    ariaStop: "Detener generación",
  },
};
