import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    unknownError: "Unknown error",
    branchError: "Failed to switch conversation branch",
    connected: "Connected",
    reconnecting: "Reconnecting...",
    welcomeTitle: "How can I help you today?",
    pillCreateRepo: "Create Repo",
    pillCreateRepoPrompt: "Help me create a new code repository.",
    pillListAgents: "List Agents",
    pillListAgentsPrompt: "List all active programmatic agents and their roles.",
    pillStartLab: "Start Experiment",
    pillStartLabPrompt: "Explain how to configure and run a debate experiment in the Laboratory.",
    pillAnalyzeCode: "Analyze Workspace",
    pillAnalyzeCodePrompt: "Analyze the current repository structure and describe its architecture.",
    pillRunTests: "Run Tests",
    pillRunTestsPrompt: "Run the project's test suite and report if any checks fail.",
    pillAgentRole: "Describe Role",
    pillAgentRolePrompt: "Explain your system prompt, context, and capabilities.",
    newMessages: "New messages",
  },
  es: {
    unknownError: "Error desconocido",
    branchError: "Error al cambiar de rama de conversacion",
    connected: "Conectado",
    reconnecting: "Reconectando...",
    welcomeTitle: "¿En qué te puedo ayudar hoy?",
    pillCreateRepo: "Crear Repo",
    pillCreateRepoPrompt: "Ayudame a crear un nuevo repositorio de código.",
    pillListAgents: "Listar Agentes",
    pillListAgentsPrompt: "Listá los agentes programáticos activos y sus roles.",
    pillStartLab: "Iniciar Experimento",
    pillStartLabPrompt: "Explicame cómo configurar y ejecutar una simulación de debate en el Laboratorio.",
    pillAnalyzeCode: "Analizar Workspace",
    pillAnalyzeCodePrompt: "Analizá la estructura del repositorio actual y describí su arquitectura.",
    pillRunTests: "Ejecutar Tests",
    pillRunTestsPrompt: "Corré las pruebas del proyecto y reportá si hay fallas.",
    pillAgentRole: "Describir Rol",
    pillAgentRolePrompt: "Explicame cuál es tu prompt del sistema, contexto y capacidades.",
    newMessages: "Nuevos mensajes",
  },
};
