import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    title: "Delegated Tasks",
    subtitle: "Tasks outsourced to programmatic subagents to keep context clean",
    noActiveSession: "No Active Session",
    noActiveSessionDesc: "Please select or start a chat session to view its delegated tasks.",
    noDelegations: "No Delegations",
    noDelegationsDesc: "This session hasn't delegated any tasks to other subagents yet.",
    thTask: "Task",
    thTarget: "Target",
    thStatus: "Status",
    thStarted: "Started",
    thCompleted: "Completed",
    running: "Running",
    success: "Success",
    error: "Error",
    blocked: "Blocked",
    actionNavigate: "View subsession",
    details: "Result Details",
    executiveSummary: "Executive Summary",
    artifacts: "Produced Artifacts",
    risks: "Identified Risks",
    closeDetails: "Hide details",
  },
  es: {
    title: "Tareas Delegadas",
    subtitle: "Tareas externalizadas a subagentes programáticos para mantener limpio el contexto",
    noActiveSession: "Sin Sesión Activa",
    noActiveSessionDesc: "Por favor selecciona o inicia una sesión de chat para ver sus tareas delegadas.",
    noDelegations: "Sin Delegaciones",
    noDelegationsDesc: "Esta sesión no ha delegado ninguna tarea a otros subagentes todavía.",
    thTask: "Tarea",
    thTarget: "Objetivo",
    thStatus: "Estado",
    thStarted: "Iniciada",
    thCompleted: "Completada",
    running: "Ejecutando",
    success: "Completada",
    error: "Error",
    blocked: "Bloqueada",
    actionNavigate: "Ver subsesión",
    details: "Detalles del Resultado",
    executiveSummary: "Resumen Ejecutivo",
    artifacts: "Artefactos Producidos",
    risks: "Riesgos Identificados",
    closeDetails: "Ocultar detalles",
  },
};
