import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    toolReadName: "Read File",
    toolReadDesc: "Read content of files on disk",
    toolWriteName: "Write File",
    toolWriteDesc: "Create new files on disk",
    toolEditName: "Edit File",
    toolEditDesc: "Modify existing files on disk",
    toolBashName: "Bash Command",
    toolBashDesc: "Execute shell commands on host",
    toolGrepName: "Grep Search",
    toolGrepDesc: "Find pattern matches within files",
    toolFindName: "Find Files",
    toolFindDesc: "Locate files in directory structure",
    toolLsName: "Directory List",
    toolLsDesc: "List directory contents",
    fullAccess: "Autonomous",
    standard: "Standard",
    readOnly: "Read-Only",
    restricted: "Restricted (0 tools)",
  },
  es: {
    toolReadName: "Leer Archivo",
    toolReadDesc: "Lee el contenido de archivos en disco",
    toolWriteName: "Escribir Archivo",
    toolWriteDesc: "Crea nuevos archivos en disco",
    toolEditName: "Editar Archivo",
    toolEditDesc: "Modifica archivos existentes en disco",
    toolBashName: "Comando Bash",
    toolBashDesc: "Ejecuta comandos de shell en el host",
    toolGrepName: "Busqueda Grep",
    toolGrepDesc: "Encuentra coincidencias de patrones en archivos",
    toolFindName: "Buscar Archivos",
    toolFindDesc: "Localiza archivos en la estructura de directorios",
    toolLsName: "Listar Directorio",
    toolLsDesc: "Lista el contenido del directorio",
    fullAccess: "Autónomo",
    standard: "Estándar",
    readOnly: "Solo Lectura",
    restricted: "Restringido (0 herramientas)",
  },
};
