import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    deleting: "Deleting...",
    delete: "Delete",
    chat: "Chat",
    history: "History",
    edit: "Edit",
    pageTitle: "Agents",
    pageSubtitle: "Programmatic agents — independent AI workers with isolated workspaces",
    refresh: "Refresh",
    registerAgent: "Register Agent",
    emptyTitle: "No agents running",
    emptyDescription: "Register your first agent to get started",
    registerAgentBtn: "Register Agent",
    editAgent: "Edit Agent",
    registerAgentTitle: "Register Agent",
    editAgentDesc: "Modify the agent configuration",
    registerAgentDesc: "Define a new programmatic agent",
    idField: "ID *",
    nameField: "Name *",
    roleField: "Role *",
    portField: "Port (optional)",
    modelField: "Model (optional)",
    skillsField: "Skills (comma-separated)",
    systemPromptField: "System Prompt *",
    idPlaceholder: "web-builder",
    namePlaceholder: "Web Builder",
    rolePlaceholder: "web-builder",
    portPlaceholder: "4200",
    modelPlaceholder: "e.g. GPT 5.6 Terra",
    skillsPlaceholder: "github-deploy, cloudflare-deploy",
    systemPromptPlaceholder: "You are an expert web developer specializing in React and TypeScript...",
    saving: "Saving...",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    execTitle: "Execution History",
    execSubtitle: "Analyze performance and logs of delegated tasks",
    noExecutions: "No executions recorded.",
    loadExecError: "Failed to load executions",
    selectExecHint: "Select an execution to view details",
    execDuration: "Execution Duration",
    execStatus: "Status",
    seconds: " seconds",
    success: "Successful",
    errors: " Error(s)",
    errorsFound: "Errors Found",
    executedTools: "Executed Tools",
    noTools: "No tools were executed in this task.",
    running: "running",
    sessionMessages: "Session Messages",
    prompt: "Prompt",
    arguments: "Arguments",
    result: "Result",
    saveError: "Failed to save agent",
    idPatternTitle: "lowercase letters, numbers, and dashes only",
    deleteConfirm_1: 'Are you sure you want to delete agent "',
    deleteConfirm_2: '"? This will stop its server and permanently delete all its associated chat sessions.',
    avatarField: "Avatar",
    avatarRemove: "Remove avatar",
    tabMyAgents: "My Agents",
    tabGallery: "Gallery",
    searchPlaceholder: "Search templates...",
    filterAll: "All",
    filterAgents: "Agents",
    filterChannels: "Teams",
    install: "Install",
    installing: "Installing...",
    installed: "Installed",
    author: "Author",
    version: "Version",
    rating: "Rating",
    compatibility: "Compatibility",
    systemPromptPreview: "System Prompt Preview",
    skillsTitle: "Skills Required",
    modelTitle: "Default Model",
    tagsTitle: "Tags",
    channelMembersTitle: "Team Members",
    replyModeTitle: "Reply Mode",
    installSuccessAgent: "Agent installed successfully!",
    installSuccessChannel: "Team installed successfully!",
    installError: "Failed to install template",
    viewDetail: "View Details",
    advancedConfig: "Advanced Configuration",
    serialToolsLabel: "Serial Tools (Interactive)",
    serialToolsDescription: "Select the tools that will suspend agent execution to wait for your approval or input.",
    blueprintIdLabel: "Blueprint ID",
    createdAtLabel: "Created At",
  },
  es: {
    deleting: "Eliminando...",
    delete: "Eliminar",
    chat: "Chat",
    history: "Historial",
    edit: "Editar",
    pageTitle: "Agentes",
    pageSubtitle: "Agentes programáticos — trabajadores IA independientes con workspaces aislados",
    refresh: "Actualizar",
    registerAgent: "Registrar Agente",
    emptyTitle: "No hay agentes activos",
    emptyDescription: "Registra tu primer agente para empezar",
    registerAgentBtn: "Registrar Agente",
    editAgent: "Editar Agente",
    registerAgentTitle: "Registrar Agente",
    editAgentDesc: "Modifica la configuración del agente",
    registerAgentDesc: "Define un nuevo agente programático",
    idField: "ID *",
    nameField: "Nombre *",
    roleField: "Rol *",
    portField: "Puerto (opcional)",
    modelField: "Modelo (opcional)",
    skillsField: "Skills (separadas por coma)",
    systemPromptField: "Prompt de Sistema *",
    idPlaceholder: "web-builder",
    namePlaceholder: "Web Builder",
    rolePlaceholder: "web-builder",
    portPlaceholder: "4200",
    modelPlaceholder: "ej. GPT 5.6 Terra",
    skillsPlaceholder: "github-deploy, cloudflare-deploy",
    systemPromptPlaceholder: "Eres un desarrollador web experto especializado en React y TypeScript...",
    saving: "Guardando...",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    execTitle: "Historial de Ejecuciones",
    execSubtitle: "Analiza el rendimiento y logs de tareas delegadas",
    noExecutions: "Sin ejecuciones registradas.",
    loadExecError: "Error al cargar ejecuciones",
    selectExecHint: "Selecciona una ejecución para ver el detalle",
    execDuration: "Duración de Ejecución",
    execStatus: "Estado",
    seconds: " segundos",
    success: "Exitosa",
    errors: " Error(es)",
    errorsFound: "Errores Encontrados",
    executedTools: "Herramientas Ejecutadas",
    noTools: "No se ejecutaron herramientas en esta tarea.",
    running: "corriendo",
    sessionMessages: "Mensajes de Sesión",
    prompt: "Prompt",
    arguments: "Argumentos",
    result: "Resultado",
    saveError: "Error al guardar el agente",
    idPatternTitle: "solo minúsculas, números y guiones",
    deleteConfirm_1: "¿Estás seguro de que quieres eliminar al agente \"",
    deleteConfirm_2: "\"? Esto detendrá su servidor y eliminará todas sus sesiones de chat asociadas de manera permanente.",
    avatarField: "Avatar",
    avatarRemove: "Eliminar avatar",
    tabMyAgents: "Mis Agentes",
    tabGallery: "Galería",
    searchPlaceholder: "Buscar plantillas...",
    filterAll: "Todos",
    filterAgents: "Agentes",
    filterChannels: "Equipos",
    install: "Instalar",
    installing: "Instalando...",
    installed: "Instalado",
    author: "Autor",
    version: "Versión",
    rating: "Puntuación",
    compatibility: "Compatibilidad",
    systemPromptPreview: "Vista Previa de Prompt",
    skillsTitle: "Skills Requeridas",
    modelTitle: "Modelo por Defecto",
    tagsTitle: "Etiquetas",
    channelMembersTitle: "Miembros del Equipo",
    replyModeTitle: "Modo de Respuesta",
    installSuccessAgent: "¡Agente instalado correctamente!",
    installSuccessChannel: "¡Equipo instalado correctamente!",
    installError: "Error al instalar la plantilla",
    viewDetail: "Ver Detalles",
    advancedConfig: "Configuracion Avanzada",
    serialToolsLabel: "Herramientas Seriales (Interactivas)",
    serialToolsDescription: "Selecciona las herramientas que pausaran la ejecucion del agente para esperar tu aprobacion o respuesta.",
    blueprintIdLabel: "ID del Blueprint",
    createdAtLabel: "Creado el",
  },
};
