import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    title: "Global Sessions Analytics",
    subtitle: "Consolidated performance and resource metrics across all agent sessions",
    filterFrom: "From",
    filterTo: "To",
    filterProject: "Project",
    filterAgent: "Agent",
    filterChannel: "Team",
    allProjects: "All Projects",
    allAgents: "All Agents",
    allChannels: "All Teams",
    kpiSessions: "Total Sessions",
    kpiTokens: "Tokens Consumed",
    kpiToolCalls: "Tool Calls",
    kpiAvgDuration: "Avg Session Duration",
    kpiErrorRate: "Session Error Rate",
    chartActivityTitle: "Session & Token Activity Over Time",
    chartToolsTitle: "Top Tools Executed",
    chartModelsTitle: "Model Distribution",
    chartErrorsTitle: "Failures by Tool",
    loading: "Loading analytics data...",
    noData: "No metrics data found for the selected filters",
    seconds: "s",
    minutes: "m",
    hours: "h",
  },
  es: {
    title: "Analíticas de Sesiones Globales",
    subtitle: "Métricas consolidadas de rendimiento y recursos de todas las sesiones",
    filterFrom: "Desde",
    filterTo: "Hasta",
    filterProject: "Proyecto",
    filterAgent: "Agente",
    filterChannel: "Equipo",
    allProjects: "Todos los proyectos",
    allAgents: "Todos los agentes",
    allChannels: "Todos los equipos",
    kpiSessions: "Sesiones Totales",
    kpiTokens: "Tokens Consumidos",
    kpiToolCalls: "Llamadas a Herramientas",
    kpiAvgDuration: "Duración Promedio",
    kpiErrorRate: "Tasa de Error",
    chartActivityTitle: "Actividad de Sesiones y Tokens en el Tiempo",
    chartToolsTitle: "Herramientas Más Ejecutadas",
    chartModelsTitle: "Distribución de Modelos",
    chartErrorsTitle: "Fallas por Herramienta",
    loading: "Cargando datos analíticos...",
    noData: "No se encontraron métricas para los filtros seleccionados",
    seconds: "s",
    minutes: "m",
    hours: "h",
  },
};
