import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    title: "Dashboard",
    subtitle: "Overview of your active workspace projects, team channels, agents, and running execution sessions.",
    workspaceGlobal: "Global Workspace",
    newProject: "+ New Project",
    loading: "Loading dashboard data...",
    id: "ID:",
    lastModified: "Last modified:",
    open: "Open",
    renameTooltip: "Rename Project",
    deleteTooltip: "Delete Project",
    emptyTitle: "No projects yet",
    emptyDescription: "Create or clone a repository to start working with the agent.",
    emptyButton: "Create project",
    createModalTitle: "New Project / Repository",
    projectNameLabel: "Project Name",
    projectNamePlaceholder: "e.g. my-web-app",
    cloneUrlLabel: "Git Clone URL (Optional)",
    cloneUrlPlaceholder: "e.g. https://github.com/user/repo.git",
    cancel: "Cancel",
    creating: "Creating...",
    createProject: "Create Project",
    renameModalTitle: "Rename Project",
    newNameLabel: "New Project Name",
    save: "Save",
    deleteModalTitle: "Delete Project",
    deleteDescription: "This action is destructive. It will permanently delete the code folder, uploaded files, and all associated chat sessions.",
    confirmLabel: "Write {name} to confirm:",
    projectNamePlaceholderDelete: "Project name",
    deleting: "Deleting...",
    deleteAnyway: "Delete anyway",
    fetchError: "Failed to fetch repositories",
    loadError: "Failed to load dashboard data",
    renameError: "Failed to rename project",
    deleteError: "Failed to delete project",
    createError: "Failed to create project",
    infoModalTitle: "Project Details",
    cloneUrlLabelEditable: "Git Clone URL",
    createdAtLabel: "Created At",
    diskPathLabel: "Disk Path",
    copyId: "Copy ID",
    copied: "Copied!",
    saveChanges: "Save Changes",
    noValue: "None",
    saving: "Saving...",
    welcomeBack: "Welcome Back",
    projectsSection: "Active Projects",
    teamsSection: "Active Teams",
    agentsSection: "Agents Team",
    sessionsSection: "Active Sessions",
    operationalNow: "What is in progress now",
    recentWorkspaces: "Recent workspaces",
    noActiveSessions: "No active sessions running right now.",
    avatarUrlLabel: "Avatar/Image URL (Optional)",
    avatarUrlPlaceholder: "e.g. https://example.com/avatar.png",
    membersCount: "{count} members",
    messagesCount: "{count} messages",
    viewAll: "View All",
  },
  es: {
    title: "Dashboard",
    subtitle: "Resumen de tus proyectos activos, canales de equipo, agentes y sesiones de ejecuci\u00f3n en curso.",
    workspaceGlobal: "Workspace Global",
    newProject: "+ Nuevo Proyecto",
    loading: "Cargando datos del dashboard...",
    id: "ID:",
    lastModified: "\u00daltima modificaci\u00f3n:",
    open: "Abrir",
    renameTooltip: "Renombrar Proyecto",
    deleteTooltip: "Eliminar Proyecto",
    emptyTitle: "No hay proyectos",
    emptyDescription: "Crea o clona un repositorio para empezar a trabajar con el agente.",
    emptyButton: "Crear proyecto",
    createModalTitle: "Nuevo Proyecto / Repositorio",
    projectNameLabel: "Nombre del Proyecto",
    projectNamePlaceholder: "ej. mi-app-web",
    cloneUrlLabel: "URL de Clonaci\u00f3n Git (Opcional)",
    cloneUrlPlaceholder: "ej. https://github.com/usuario/repo.git",
    cancel: "Cancelar",
    creating: "Creando...",
    createProject: "Crear Proyecto",
    renameModalTitle: "Renombrar Proyecto",
    newNameLabel: "Nuevo Nombre del Proyecto",
    save: "Guardar",
    deleteModalTitle: "Eliminar Proyecto",
    deleteDescription: "Esta acci\u00f3n es destructiva. Se borrar\u00e1 la carpeta de c\u00f3digo, los archivos subidos y todas las sesiones de chat asociadas.",
    confirmLabel: "Escrib\u00ed {name} para confirmar:",
    projectNamePlaceholderDelete: "Nombre del proyecto",
    deleting: "Eliminando...",
    deleteAnyway: "Eliminar de todos modos",
    fetchError: "Error al cargar los repositorios",
    loadError: "Error al cargar los datos del dashboard",
    renameError: "Error al renombrar el proyecto",
    deleteError: "Error al eliminar el proyecto",
    createError: "Error al crear el proyecto",
    infoModalTitle: "Detalles del Proyecto",
    cloneUrlLabelEditable: "URL de Clonaci\u00f3n Git",
    createdAtLabel: "Creado el",
    diskPathLabel: "Ruta en Disco",
    copyId: "Copiar ID",
    copied: "Copiado!",
    saveChanges: "Guardar Cambios",
    noValue: "Ninguno",
    saving: "Guardando...",
    welcomeBack: "Bienvenido de nuevo",
    projectsSection: "Proyectos Activos",
    teamsSection: "Equipos Activos",
    agentsSection: "Equipo de Agentes",
    sessionsSection: "Sesiones Activas",
    operationalNow: "Lo que está en curso ahora",
    recentWorkspaces: "Espacios de trabajo recientes",
    noActiveSessions: "No hay sesiones activas en ejecuci\u00f3n ahora mismo.",
    avatarUrlLabel: "URL del Avatar/Imagen (Opcional)",
    avatarUrlPlaceholder: "ej. https://ejemplo.com/avatar.png",
    membersCount: "{count} miembros",
    messagesCount: "{count} mensajes",
    viewAll: "Ver Todo",
  },
};
