import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    tabSessions: "Streaming Sessions",
    tabLogs: "System Traces",
    filterAll: "All",
    filterSession: "Session",
    filterChannel: "Channel",
    statusActive: "Active",
    statusInactive: "Inactive",
    statusStreaming: "Streaming...",
    statusTaskRunning: "Task Running...",
    statusMomentsAgo: "Just now",
    statusMinutesAgo: "minute",
    statusHoursAgo: "hour",
    statusNoActivity: "No activity recorded",
    labelSourceSession: "Session",
    labelSourceChannel: "Channel",
    labelUser: "User:",
    labelResponse: "Response:",
    labelWriting: "Writing:",
    labelThinking: "Thinking:",
    labelToolStart: "Tool Start:",
    labelToolEnd: "Tool End:",
    toolSuccess: "success",
    toolError: "error",
    labelError: "Error",
    labelResultTruncated: "(result truncated)",
    labelActivity: "Activity",
    openChat: "Open Chat",
    sourceLabel: "Source:",
    badgeGlobal: "Global",
    badgeProject: "Project:",
    badgeChannel: "Channel:",
    badgeAgent: "Agent:",
    loadingSessions: "Loading sessions...",
    noActiveSessions: "No active sessions at this moment.",
    scrollToTop: "Scroll to Top",
    autoScroll: "Auto-scroll",
    clear: "Clear",
    loadMore: "Load older logs",
    consoleControls: "Console Controls",
  },
  es: {
    tabSessions: "Sesiones en Streaming",
    tabLogs: "Trazas de Sistema",
    filterAll: "Todos",
    filterSession: "Sesion",
    filterChannel: "Canal",
    statusActive: "Activa",
    statusInactive: "Inactiva",
    statusStreaming: "Streaming...",
    statusTaskRunning: "Task Running...",
    statusMomentsAgo: "Hace unos instantes",
    statusMinutesAgo: "minuto",
    statusHoursAgo: "hora",
    statusNoActivity: "Sin actividad registrada",
    labelSourceSession: "Sesion",
    labelSourceChannel: "Canal",
    labelUser: "Usuario:",
    labelResponse: "Respuesta:",
    labelWriting: "Escribiendo:",
    labelThinking: "Pensando:",
    labelToolStart: "Inicio de Herramienta:",
    labelToolEnd: "Fin de Herramienta:",
    toolSuccess: "exitoso",
    toolError: "error",
    labelError: "Error",
    labelResultTruncated: "(resultado truncado)",
    labelActivity: "Actividad",
    openChat: "Abrir Chat",
    sourceLabel: "Origen:",
    badgeGlobal: "Global",
    badgeProject: "Proyecto:",
    badgeChannel: "Canal:",
    badgeAgent: "Agente:",
    loadingSessions: "Cargando sesiones...",
    noActiveSessions: "No hay sesiones activas en este momento.",
    scrollToTop: "Ir al inicio",
    autoScroll: "Auto-scroll",
    clear: "Limpiar",
    loadMore: "Cargar logs anteriores",
    consoleControls: "Controles de Consola",
  },
};
