import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    tabGallery: "Official Gallery",
    tabCustom: "Custom Servers",
    customComingSoon: "Custom MCP servers are coming soon.",
    customComingSoonDesc: "You'll be able to add custom stdio and HTTP MCP servers. Stay tuned!",
    addCustomServer: "Add Custom Server",
    noCustomServers: "No Custom Servers",
    noCustomServersDesc: "Create local MCP integrations running node/python scripts, or point to external microservices compatible with the protocol.",
    installing: "Installing...",
    validating: "Validating...",
    installedSuccess: "installed successfully. Starting connection...",
    connected: "Connected to",
    disconnected: "disconnected.",
    uninstalled: "uninstalled.",
    enabled: "enabled",
    disabled: "disabled",
    validationSuccess: "Validation successful! Discovered tools:",
    validationFailed: "Validation failed for",
    connectionFailed: "Connection test failed on server",
    saveSuccess: "Server saved.",
    testFailed: "Connection test failed",
    rawEditor: "Raw Config",
    rawEditorTitle: "Raw Configuration Editor",
    customServers: "Custom Servers",
    all: "All",
    fetchError: "Failed to load MCP Marketplace data",
    categoryGeneral: "General",
  },
  es: {
    tabGallery: "Galería Oficial",
    tabCustom: "Servidores Custom",
    customComingSoon: "Servidores MCP personalizados próximamente.",
    customComingSoonDesc: "Podrás agregar servidores MCP stdio y HTTP personalizados. ¡Muy pronto!",
    addCustomServer: "Agregar Servidor Custom",
    noCustomServers: "Sin Servidores Personalizados",
    noCustomServersDesc: "Crea integraciones MCP locales ejecutando scripts de node/python, o apunta a microservicios externos compatibles con el protocolo.",
    installing: "Instalando...",
    validating: "Validando...",
    installedSuccess: "instalado con éxito. Iniciando conexión...",
    connected: "Conectado a",
    disconnected: "desconectado.",
    uninstalled: "desinstalado.",
    enabled: "habilitado",
    disabled: "deshabilitado",
    validationSuccess: "¡Validación exitosa! Herramientas descubiertas:",
    validationFailed: "Fallo al validar",
    connectionFailed: "Error al conectar con el servidor",
    saveSuccess: "Servidor guardado.",
    testFailed: "Fallo en la prueba de conexión",
    rawEditor: "Config Raw",
    rawEditorTitle: "Editor de Configuración Raw",
    customServers: "Servidores Personalizados",
    all: "Todos",
    fetchError: "Fallo al inicializar datos de MCP",
    categoryGeneral: "General",
  },
};
