import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    pluginsTitle: "Add-ons & Plugins",
    pluginsSubtitle: "Extend the capabilities of your agents with persistent memory and advanced web search integrations.",
    cardMemoryTitle: "Persistent Agent Memory",
    cardMemoryDesc: "Gives agents long-term memory using local SQLite with full-text search (FTS5). Store facts, events, and patterns — retrieved by relevance. 100% local, zero external calls.",
    cardExaTitle: "Exa Neural Web Search",
    cardExaDesc: "Enables agents to perform grounded web search with neural embeddings, excerpt extraction, and structured synthesis.",
    statusEnabled: "Active",
    statusDisabled: "Inactive",
    statusConfigured: "Configured",
    statusMissingKey: "Missing API Key",
    enablePlugin: "Enable persistent memory",
    autoStoreInteractions: "Auto-store interactions (episodic memory)",
    localOnlyNotice: "Memory is isolated per session. No external API calls are made.",
    missingKeyWarning: "This plugin requires EXA_API_KEY to be configured in Settings.",
    configureKeyLink: "Go to Settings > Env Vars to configure",
    globalActivation: "Enable by default for new sessions",
    saveSuccess: "Plugins settings updated successfully.",
    fetchError: "Failed to load plugins configuration.",
    saveError: "Failed to save plugins configuration.",
  },
  es: {
    pluginsTitle: "Add-ons y Plugins",
    pluginsSubtitle: "Extiende las capacidades de tus agentes con memoria persistente e integraciones avanzadas de búsqueda web.",
    cardMemoryTitle: "Memoria Persistente para Agentes",
    cardMemoryDesc: "Otorga a los agentes memoria a largo plazo mediante SQLite local con búsqueda de texto completo (FTS5). Guarda hechos, eventos y patrones — recuperados por relevancia. 100% local, sin llamadas externas.",
    cardExaTitle: "Búsqueda Web Neural (Exa)",
    cardExaDesc: "Permite a los agentes realizar búsquedas web basadas en contexto con embeddings neuronales, extracción de citas y síntesis estructurada.",
    statusEnabled: "Activo",
    statusDisabled: "Inactivo",
    statusConfigured: "Configurado",
    statusMissingKey: "Falta API Key",
    enablePlugin: "Habilitar memoria persistente",
    autoStoreInteractions: "Auto-guardar interacciones (memoria episódica)",
    localOnlyNotice: "La memoria está aislada por sesión. No se realizan llamadas a APIs externas.",
    missingKeyWarning: "Este plugin requiere configurar EXA_API_KEY en Ajustes.",
    configureKeyLink: "Ir a Ajustes > Vars de Entorno para configurar",
    globalActivation: "Habilitar por defecto en nuevas sesiones",
    saveSuccess: "Ajustes de plugins actualizados con éxito.",
    fetchError: "Error al cargar la configuración de plugins.",
    saveError: "Error al guardar la configuración de plugins.",
  },
};
