import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    title: "Session Board",
    idleColumn: "Idle",
    workingColumn: "Working",
    doneColumn: "Done",
    idleDesc: "Sessions with no current activity",
    workingDesc: "Sessions currently executing",
    doneDesc: "Completed executions with results",
    loading: "Loading sessions...",
    noSessions: "No sessions in this column",
    badgeProject: "Project",
    badgeAgent: "Agent",
    badgeChannel: "Channel",
    badgeGlobal: "Global",
    openChat: "Open",
    statusStreaming: "Streaming",
    statusTaskRunning: "Task Running",
    statusActive: "Active",
    statusSleeping: "Inactive",
    statusDone: "Completed",
    lastActivity: "Activity",
    momentsAgo: "A moment ago",
    minutesAgo: "min",
    hoursAgo: "h",
    daysAgo: "d",
  },
  es: {
    title: "Tablero de Sesiones",
    idleColumn: "Idle",
    workingColumn: "Working",
    doneColumn: "Done",
    idleDesc: "Sesiones sin actividad actual",
    workingDesc: "Sesiones con ejecucion en curso",
    doneDesc: "Ejecuciones completadas con resultado",
    loading: "Cargando sesiones...",
    noSessions: "No hay sesiones en esta columna",
    badgeProject: "Proyecto",
    badgeAgent: "Agente",
    badgeChannel: "Canal",
    badgeGlobal: "Global",
    openChat: "Abrir",
    statusStreaming: "Streaming",
    statusTaskRunning: "Task Running",
    statusActive: "Activa",
    statusSleeping: "Inactiva",
    statusDone: "Completada",
    lastActivity: "Actividad",
    momentsAgo: "Hace un momento",
    minutesAgo: "min",
    hoursAgo: "h",
    daysAgo: "d",
  },
};
