import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    errorTitle: "Error Loading Skills",
    retry: "Retry",
    searchPlaceholder: "Search skills...",
    resetTooltip: "Reset Manager (Spaces) Skills",
    skillCount: "skill",
    scopeProject: "Project",
    scopeUser: "User",
    noSkillsFound: "No skills found",
    backToList: "Back to list",
    location: "Location:",
    scopeProjectDetail: "Project-local",
    scopeUserDetail: "User-global",
    explicitOnly: "Explicit Only",
    description: "Description",
    instructions: "Instructions",
    noInstructionText: "*No instruction text*",
    selectSkillHint: "Select a skill from the list to view its instructions",
    resetConfirm: 'Are you sure you want to reset the default Manager Skills? All manual changes to skills starting with "factory-" will be overwritten.',
    resetSuccess: "Manager skills reset successfully.",
    resetErrorPrefix: "Error resetting skills: ",
    loadError: "Failed to load skills",
  },
  es: {
    errorTitle: "Error al Cargar Skills",
    retry: "Reintentar",
    searchPlaceholder: "Buscar skills...",
    resetTooltip: "Restablecer Skills de Manager (Spaces)",
    skillCount: "skill",
    scopeProject: "Proyecto",
    scopeUser: "Usuario",
    noSkillsFound: "No se encontraron skills",
    backToList: "Volver a la lista",
    location: "Ubicacion:",
    scopeProjectDetail: "Proyecto-local",
    scopeUserDetail: "Usuario-global",
    explicitOnly: "Solo Explicito",
    description: "Descripcion",
    instructions: "Instrucciones",
    noInstructionText: "*Sin texto de instruccion*",
    selectSkillHint: "Selecciona un skill de la lista para ver sus instrucciones",
    resetConfirm: "¿Estas seguro de que quieres restablecer las Skills por defecto de Manager? Se sobrescribiran todos los cambios manuales en las skills que empiezan con 'factory-'.",
    resetSuccess: "Skills de Manager restablecidas con exito.",
    resetErrorPrefix: "Error al restablecer las skills: ",
    loadError: "Error al cargar skills",
  },
};
