import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    createTitle: "Create Team",
    createSubtitle: "Start a new multi-agent debate team",
    teamNameLabel: "Team Name *",
    teamNamePlaceholder: "e.g. tech-lead-debate",
    descriptionLabel: "Description (optional)",
    descriptionPlaceholder: "Stateless negotiation with arbitrage",
    avatarUrlLabel: "Avatar/Image URL (Optional)",
    avatarUrlPlaceholder: "e.g. https://example.com/avatar.png",
    cancel: "Cancel",
    creating: "Creating...",
    createTeam: "Create Team",
    createError: "Failed to create team",
    pageTitle: "Teams",
    pageSubtitle: "Multi-agent stateless teams for task coordination and delegation",
    refresh: "Refresh",
    emptyTitle: "No teams created",
    emptyDescription: "Create a team to coordinate tasks between multiple agents",
    emptyButton: "Create Team",
    teamTypeLabel: "Team Type",
    leaderLabel: "Team Leader *",
    selectLeaderPlaceholder: "Select a leader agent...",
    noAgentsError: "No registered agents found. Please register an agent first.",
    membersLabel: "Team Members (optional)",
    membersPlaceholder: "Select additional members...",
    avatarLabel: "Avatar",
    uploadAvatar: "Upload Image",
    removeAvatar: "Remove",
    defaultAvatarsLabel: "Default Avatars",
  },
  es: {
    createTitle: "Crear Equipo",
    createSubtitle: "Inicia un nuevo equipo de debate multi-agente",
    teamNameLabel: "Nombre del Equipo *",
    teamNamePlaceholder: "ej. debate-lideres-tecnicos",
    descriptionLabel: "Descripción (opcional)",
    descriptionPlaceholder: "Negociación stateless con arbitraje",
    avatarUrlLabel: "URL del Avatar/Imagen (Opcional)",
    avatarUrlPlaceholder: "ej. https://ejemplo.com/avatar.png",
    cancel: "Cancelar",
    creating: "Creando...",
    createTeam: "Crear Equipo",
    createError: "Error al crear el equipo",
    pageTitle: "Equipos",
    pageSubtitle: "Equipos multi-agente stateless para coordinación y delegación de tareas",
    refresh: "Actualizar",
    emptyTitle: "No hay equipos creados",
    emptyDescription: "Crea un equipo para coordinar tareas entre múltiples agentes",
    emptyButton: "Crear Equipo",
    teamTypeLabel: "Tipo de Equipo",
    leaderLabel: "Líder del Equipo *",
    selectLeaderPlaceholder: "Selecciona un agente líder...",
    noAgentsError: "No hay agentes registrados. Por favor registra un agente primero.",
    membersLabel: "Miembros del Equipo (opcional)",
    membersPlaceholder: "Selecciona miembros adicionales...",
    avatarLabel: "Avatar",
    uploadAvatar: "Subir Imagen",
    removeAvatar: "Eliminar",
    defaultAvatarsLabel: "Avatares por Defecto",
  },
};
