import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    editAgent: "Edit Agent",
    registerAgentTitle: "Register Agent",
    editAgentDesc: "Modify the agent configuration",
    registerAgentDesc: "Define a new programmatic agent",
    idField: "ID *",
    nameField: "Name *",
    roleField: "Role *",
    portField: "Port (optional)",
    modelField: "Model (optional)",
    skillsField: "Skills (comma-separated)",
    systemPromptField: "System Prompt *",
    idPlaceholder: "web-builder",
    namePlaceholder: "Web Builder",
    rolePlaceholder: "web-builder",
    portPlaceholder: "4200",
    modelPlaceholder: "e.g. GPT 5.6 Terra",
    skillsPlaceholder: "github-deploy, cloudflare-deploy",
    systemPromptPlaceholder: "You are an expert web developer specializing in React and TypeScript...",
    saving: "Saving...",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    saveError: "Failed to save agent",
    idPatternTitle: "lowercase letters, numbers, and dashes only",
    advancedConfig: "Advanced Configuration",
    serialToolsLabel: "Serial Tools (Interactive)",
    serialToolsDescription: "Select the tools that will suspend agent execution to wait for your approval or input.",
    blueprintIdLabel: "Blueprint ID",
    createdAtLabel: "Created At",
  },
  es: {
    editAgent: "Editar Agente",
    registerAgentTitle: "Registrar Agente",
    editAgentDesc: "Modifica la configuración del agente",
    registerAgentDesc: "Define un nuevo agente programático",
    idField: "ID *",
    nameField: "Nombre *",
    roleField: "Rol *",
    portField: "Puerto (opcional)",
    modelField: "Modelo (opcional)",
    skillsField: "Skills (separadas por coma)",
    systemPromptField: "Prompt de Sistema *",
    idPlaceholder: "web-builder",
    namePlaceholder: "Web Builder",
    rolePlaceholder: "web-builder",
    portPlaceholder: "4200",
    modelPlaceholder: "ej. GPT 5.6 Terra",
    skillsPlaceholder: "github-deploy, cloudflare-deploy",
    systemPromptPlaceholder: "Eres un desarrollador web experto especializado en React y TypeScript...",
    saving: "Guardando...",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    saveError: "Error al guardar el agente",
    idPatternTitle: "solo minúsculas, números y guiones",
    advancedConfig: "Configuracion Avanzada",
    serialToolsLabel: "Herramientas Seriales (Interactivas)",
    serialToolsDescription: "Selecciona las herramientas que pausaran la ejecucion del agente para esperar tu aprobacion o respuesta.",
    blueprintIdLabel: "ID del Blueprint",
    createdAtLabel: "Creado el",
  },
};
