import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    appearance: "Appearance",
    mcpLink: "MCP Configuration",
    mcpDesc: "Manage Model Context Protocol servers",
    language: "Language",

    activeSession: "Active Session",
    signOut: "Sign Out",

    aiToolsConfig: "AI Tools Configuration",
    aiToolsDesc: "Configure dedicated models for vision analysis and image generation tools.",
    loadingModels: "Loading model configurations...",

    visionModel: "Vision Model (for programmatic vision tool)",
    selectVisionModel: "-- Select Vision Model --",
    diagnoseVision: "Diagnose Vision Model",
    promptAnalyzeImage: "Prompt to analyze the image...",
    uploadImage: "Upload Image",
    imageLoaded: "Image Loaded",
    clear: "Clear",
    analyzingImage: "Analyzing Image...",
    runVisionTest: "Run Diagnostic Vision Test",
    response: "Response:",
    diagnosticFailure: "Diagnostic Failure:",

    imageGenModel: "Image Generation Model",
    selectImageGenModel: "-- Select Image Generation Model --",
    videoGenModel: "Video Generation Model",
    selectVideoGenModel: "-- Select Video Generation Model --",
    perVideo: "/ video",
    cost: "Cost",
    rateLimit: "Rate Limit",
    concurrency: "Concurrency",
    perImage: "/ image",
    rpm: "RPM",
    concurrent: "concurrent",
    diagnoseImageGen: "Diagnose Image Generation Model",
    promptGenerateImage: "Prompt to generate image...",
    generating: "Generating...",
    generateTestImage: "Generate Test Image",
    imageGenerated: "Image Generated Successfully!",
    loadingImagePreview: "Loading image preview...",
    videoGenEnabled: "Enable Video Generation Tool",
    diagnoseVideoGen: "Diagnose Video Generation Model",
    promptGenerateVideo: "Prompt to generate video...",
    generatingVideo: "Generating Video...",
    generateTestVideo: "Generate Test Video",
    videoGenerated: "Video Generated Successfully!",
    loadingVideoPreview: "Loading video preview...",

    openMCP: "Open MCP Marketplace",

    password: "Password",
    change: "Change",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    passwordUpdated: "Password updated successfully.",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    allFieldsRequired: "All fields are required",
    passwordsDoNotMatch: "New passwords do not match",
    passwordMinLength: "New password must be at least 8 characters",
    failedChangePassword: "Failed to change password",

    systemStatus: "System Status",
    apiBaseUrl: "API Base URL",
    sessionStorage: "Session Storage",
    workspaceContext: "Workspace Context",
    healthStatus: "Health Status",
    online: "Online",
    jwtFilesystem: "JWT + Server Filesystem",

    backupPortability: "Backup & Portability",
    backupDesc: "Export your configuration and workspaces or import a zip backup.",
    exportOptions: "Export Options",
    lightweight: "Lightweight (Configs, custom skills, agent/channel definitions)",
    fullBackup: "Full Backup (Includes repos & uploads, skips node_modules)",
    exportDownload: "Export & Download",
    generatingBackup: "Generating Backup...",
    importBackup: "Import Backup",
    importMode: "Import Mode",
    selectZipFile: "Select ZIP File",
    importMerge: "Import & Merge",
    restoreOverwrite: "Restore Backup (Wipe & Write)",
    importingBackup: "Importing Backup...",
    errorExporting: "Error exporting backup",
    errorImporting: "Error importing backup",
    backupImported: "Backup imported successfully via {mode} mode.",

    destructiveOverwrite: "Destructive Overwrite Action",
    overwriteWarning1: "You are about to restore a backup using",
    overwriteModeLabel: "Overwrite",
    overwriteWarning2: "mode. This will permanently delete all your existing configuration, credentials, agents, channels, and projects.",
    safeRecommendation: "Safe Recommendation:",
    backupRecommendation: "We highly recommend exporting and downloading a backup of your current setup before overwriting.",
    downloadBackupNow: "Download Backup Now",
    typeOverwriteConfirm: 'Type "OVERWRITE" to confirm',
    overwritePlaceholder: "OVERWRITE",
    confirmWipe: "Confirm & Wipe",
    overwriteMode: "Overwrite",
    mergeMode: "Merge (Keep current, update matching)",
    subagents: "Subagents",
    subagentMaxDepth: "Maximum Nesting Depth",
    subagentMaxDepthDesc: "Limit how deep subagents can recursively spawn or delegate. A value of 1 restricts execution to direct subagents only.",
    warningMaxDepth: "Higher values can lead to exponential token usage and resource consumption.",
    noSubagents: "0 - No subagents allowed",
    directSubagentsOnly: "1 - Direct subagents only (recommended)",
    nestedSubagents: "{depth} - Nested subagents allowed",
  },
  es: {
    appearance: "Apariencia",
    mcpLink: "Configuracion MCP",
    mcpDesc: "Administra servidores Model Context Protocol",
    language: "Idioma",

    activeSession: "Sesion Activa",
    signOut: "Cerrar Sesion",

    aiToolsConfig: "Configuracion de Herramientas IA",
    aiToolsDesc: "Configura modelos dedicados para analisis de vision y generacion de imagenes.",
    loadingModels: "Cargando configuraciones de modelos...",

    visionModel: "Modelo de Vision (para herramienta programatica)",
    selectVisionModel: "-- Seleccionar Modelo de Vision --",
    diagnoseVision: "Diagnosticar Modelo de Vision",
    promptAnalyzeImage: "Prompt para analizar la imagen...",
    uploadImage: "Subir Imagen",
    imageLoaded: "Imagen Cargada",
    clear: "Limpiar",
    analyzingImage: "Analizando Imagen...",
    runVisionTest: "Ejecutar Diagnostico de Vision",
    response: "Respuesta:",
    diagnosticFailure: "Fallo en el Diagnostico:",

    imageGenModel: "Modelo de Generacion de Imagenes",
    selectImageGenModel: "-- Seleccionar Modelo de Generacion --",
    videoGenModel: "Modelo de Generación de Video",
    selectVideoGenModel: "-- Seleccionar Modelo de Generación de Video --",
    perVideo: "/ video",
    cost: "Costo",
    rateLimit: "Limite de Peticiones",
    concurrency: "Concurrencia",
    perImage: "/ imagen",
    rpm: "RPM",
    concurrent: "concurrente",
    diagnoseImageGen: "Diagnosticar Generacion de Imagenes",
    promptGenerateImage: "Prompt para generar imagen...",
    generating: "Generando...",
    generateTestImage: "Generar Imagen de Prueba",
    imageGenerated: "Imagen Generada Exitosamente!",
    loadingImagePreview: "Cargando vista previa...",
    videoGenEnabled: "Activar Herramienta de Generación de Video",
    diagnoseVideoGen: "Diagnosticar Modelo de Generación de Video",
    promptGenerateVideo: "Prompt para generar video...",
    generatingVideo: "Generando Video...",
    generateTestVideo: "Generar Video de Prueba",
    videoGenerated: "¡Video Generado Exitosamente!",
    loadingVideoPreview: "Cargando vista previa del video...",

    openMCP: "Abrir MCP Marketplace",

    password: "Contrasena",
    change: "Cambiar",
    currentPassword: "Contrasena actual",
    newPassword: "Nueva contrasena",
    confirmPassword: "Confirmar nueva contrasena",
    passwordUpdated: "Contrasena actualizada exitosamente.",
    save: "Guardar",
    saving: "Guardando...",
    cancel: "Cancelar",
    allFieldsRequired: "Todos los campos son obligatorios",
    passwordsDoNotMatch: "Las contrasenas nuevas no coinciden",
    passwordMinLength: "La nueva contrasena debe tener al menos 8 caracteres",
    failedChangePassword: "Error al cambiar la contrasena",

    systemStatus: "Estado del Sistema",
    apiBaseUrl: "URL Base de la API",
    sessionStorage: "Almacenamiento de Sesion",
    workspaceContext: "Contexto del Espacio de Trabajo",
    healthStatus: "Estado de Salud",
    online: "En Linea",
    jwtFilesystem: "JWT + Sistema de Archivos",

    backupPortability: "Copia de Seguridad y Portabilidad",
    backupDesc: "Exporta tu configuracion y espacios de trabajo o importa un backup ZIP.",
    exportOptions: "Opciones de Exportacion",
    lightweight: "Ligero (Configuraciones, skills personalizados, definiciones de agentes/canales)",
    fullBackup: "Completo (Incluye repositorios y subidas, excluye node_modules)",
    exportDownload: "Exportar y Descargar",
    generatingBackup: "Generando Backup...",
    importBackup: "Importar Backup",
    importMode: "Modo de Importacion",
    selectZipFile: "Seleccionar Archivo ZIP",
    importMerge: "Importar y Combinar",
    restoreOverwrite: "Restaurar Backup (Borrar y Escribir)",
    importingBackup: "Importando Backup...",
    errorExporting: "Error al exportar el backup",
    errorImporting: "Error al importar el backup",
    backupImported: "Backup importado exitosamente via modo {mode}.",

    destructiveOverwrite: "Accion de Sobrescritura Destructiva",
    overwriteWarning1: "Estas por restaurar un backup usando el modo",
    overwriteModeLabel: "Sobrescritura",
    overwriteWarning2: "Esto eliminara permanentemente toda tu configuracion existente, credenciales, agentes, canales y proyectos.",
    safeRecommendation: "Recomendacion Segura:",
    backupRecommendation: "Recomendamos exportar y descargar un backup de tu configuracion actual antes de sobrescribir.",
    downloadBackupNow: "Descargar Backup Ahora",
    typeOverwriteConfirm: 'Escribi "OVERWRITE" para confirmar',
    overwritePlaceholder: "OVERWRITE",
    confirmWipe: "Confirmar y Borrar",
    overwriteMode: "Sobrescribir (Reemplazar todo)",
    mergeMode: "Combinar (Mantener actual, actualizar coincidencias)",
    subagents: "Subagentes",
    subagentMaxDepth: "Profundidad Máxima de Anidamiento",
    subagentMaxDepthDesc: "Limita qué tan profundo pueden los subagentes spawnear o delegar recursivamente. Un valor de 1 restringe la ejecución a subagentes directos.",
    warningMaxDepth: "Valores altos pueden causar consumo exponencial de tokens y recursos.",
    noSubagents: "0 - Sin subagentes",
    directSubagentsOnly: "1 - Solo subagentes directos (recomendado)",
    nestedSubagents: "{depth} - Permite subagentes anidados",
  },
};
