// SPDX-License-Identifier: MIT

export interface StepTypeSchema {
  type: string;
  description: string;
  requiredFields: string[];
  optionalFields: string[];
  fieldDescriptions: Record<string, string>;
}

export interface WorkflowContract {
  entity: string;
  description: string;
  onErrorOptions: string[];
  stepTypes: Record<string, StepTypeSchema>;
  workflowDefinitionFields: Record<string, string>;
}

export const WORKFLOW_CONTRACT: WorkflowContract = {
  entity: "workflow",
  description:
    "Engine de automatizaciones DAG compuestas por pasos paralelos o secuenciales execution, branches condicionales, sandbox de código TS/JS, delegaciones a subagentes y aprobaciones humanas.",
  onErrorOptions: ["stop", "continue", "retry"],
  workflowDefinitionFields: {
    id: "string (UUID v4 o ID único slug)",
    name: "string - Nombre visible del workflow",
    description: "string - Explicación detallada del propósito del workflow",
    scopeType: "global | team | project | agent - Alcance de disponibilidad",
    entityId: "string - ID de la entidad asociada si scopeType no es global",
    version: "number - Versión incremental del esquema",
    onError: "stop | continue | retry - Estrategia ante fallo de un paso",
    retryCount: "number - Cantidad de reintentos si onError es 'retry'",
    schedule: "string - Expresión cron opcional para ejecuciones programadas periódicas (ej: '0 */6 * * *')",
    onFailure: "object - Configuración de notificaciones/webhooks en caso de fallo del workflow ({ webhook?: { url, headers }, notify?: boolean })",
    steps: "Array<WorkflowStep> - Lista de pasos del DAG",
    createdAt: "string (ISO 8601) - Fecha de creación. Auto-generada si no se proporciona.",
    updatedAt: "string (ISO 8601) - Fecha de última modificación. Auto-actualizada en cada guardado.",
  },
  stepTypes: {
    agent: {
      type: "agent",
      description: "Delega una tarea autónoma a un agente o subagente especificado.",
      requiredFields: ["id", "type", "label", "taskTemplate"],
      optionalFields: [
        "agentId",
        "subagentType",
        "maxSteps",
        "captureOutputs",
        "dependsOn",
        "pinnedOutputs",
        "timeoutMs",
        "onError",
        "retryCount",
        "retryDelayMs",
        "errorBranch",
      ],
      fieldDescriptions: {
        id: "string - Identificador único del paso en snake_case (solo [a-z0-9_]). PROHIBIDO usar guiones (-), puntos u operadores JS.",
        type: "literal 'agent'",
        label: "string - Título legible del paso",
        taskTemplate: "string - Prompt o instrucción con interpolación de variables como {{inputs.var}} o {{$steps.step_id.outputs.res}}",
        agentId: "string - ID opcional del agente objetivo a ejecutar",
        subagentType: "builder | explorer | executor | planner - Tipo de rol del subagente",
        maxSteps: "number - Límite máximo de iteraciones del agente",
        captureOutputs: "Array<string> - Claves de salida a capturar en $steps.stepId.outputs",
        dependsOn: "Array<string> - IDs de pasos anteriores que deben finalizar antes de iniciar este paso",
        pinnedOutputs: "Record<string, unknown> - Valores fijos para saltar ejecución real (mock/test)",
        timeoutMs: "number - Timeout en milisegundos para limitar el tiempo máximo de ejecución de este paso",
        onError: "stop | continue | retry - Sobrescribe la estrategia de error global del workflow para este paso",
        retryCount: "number - Reintentos específicos si onError es 'retry'",
        retryDelayMs: "number - Espera en ms entre reintentos",
        errorBranch: "Array<string> - IDs de pasos a ejecutar como rama de contingencia ante fallo de este paso",
      },
    },
    if: {
      type: "if",
      description: "Evaluación condicional que bifurca el flujo hacia 'true' o 'false'.",
      requiredFields: ["id", "type", "label", "condition", "branches"],
      optionalFields: ["dependsOn", "pinnedOutputs"],
      fieldDescriptions: {
        id: "string - Identificador único del paso en snake_case (solo [a-z0-9_]). PROHIBIDO usar guiones (-).",
        type: "literal 'if'",
        label: "string - Título legible",
        condition: "string - Expresión JS a evaluar. Ejemplo $inputs.amount > 100 o $steps.pass_id.outputs.score > 50. Usar siempre snake_case en IDs de paso.",
        branches: "{ true?: string[], false?: string[] } - Mapeo de rama activa a IDs de pasos destino. Los pasos destino DEBEN declarar dependsOn conteniendo este step ID.",
        dependsOn: "Array<string> - Dependencias de precedencia",
      },
    },
    switch: {
      type: "switch",
      description: "Bifurcación múltiple basada en la evaluación de una expresión.",
      requiredFields: ["id", "type", "label", "condition", "branches"],
      optionalFields: ["dependsOn", "pinnedOutputs"],
      fieldDescriptions: {
        id: "string - Identificador único del paso en snake_case (solo [a-z0-9_]). PROHIBIDO usar guiones (-).",
        type: "literal 'switch'",
        label: "string - Título legible",
        condition: "string - Expresión que evalúa a un string clave (ej: '$steps.categorizer.outputs.category'). Usar snake_case.",
        branches: "Record<string, string[]> - Mapeo de resultado de expresión a IDs de pasos destino. Los pasos destino DEBEN declarar dependsOn conteniendo este step ID.",
        dependsOn: "Array<string> - Dependencias de precedencia",
      },
    },
    merge: {
      type: "merge",
      description: "Punto de convergencia que sincroniza ramas divergentes.",
      requiredFields: ["id", "type", "label"],
      optionalFields: ["dependsOn", "pinnedOutputs"],
      fieldDescriptions: {
        id: "string - Identificador único del paso en snake_case (solo [a-z0-9_]).",
        type: "literal 'merge'",
        label: "string - Título legible",
        dependsOn: "Array<string> - Pasos provenientes de las ramas que deben converger",
      },
    },
    approval: {
      type: "approval",
      description: "Pausa la ejecución del workflow requiriendo confirmación manual previa.",
      requiredFields: ["id", "type", "label", "approvalMessage"],
      optionalFields: ["dependsOn", "pinnedOutputs"],
      fieldDescriptions: {
        id: "string - Identificador único del paso en snake_case (solo [a-z0-9_]).",
        type: "literal 'approval'",
        label: "string - Título legible",
        approvalMessage: "string - Mensaje presentado al usuario para solicitar la aprobación",
        dependsOn: "Array<string> - Dependencias de precedencia",
      },
    },
    code: {
      type: "code",
      description: "Ejecuta fragmentos JS/TS en un sandbox aislado con timeout.",
      requiredFields: ["id", "type", "label", "codeSnippet"],
      optionalFields: ["codeTimeout", "dependsOn", "pinnedOutputs"],
      fieldDescriptions: {
        id: "string - Identificador único del paso en snake_case (solo [a-z0-9_]).",
        type: "literal 'code'",
        label: "string - Título legible",
        codeSnippet: "string - Código JS a ejecutar. Accede a outputs anteriores mediante $steps.step_id.outputs.field o {{step_id.outputs.field}}. Debe retornar un objeto.",
        codeTimeout: "number - Timeout en ms (default: 5000ms)",
        dependsOn: "Array<string> - Dependencias de precedencia",
      },
    },
    http: {
      type: "http",
      description: "Realiza llamadas HTTP/REST a servicios externos con soporte de autenticación y mapeo de respuestas.",
      requiredFields: ["id", "type", "label", "httpUrl"],
      optionalFields: [
        "httpMethod",
        "httpHeaders",
        "httpBody",
        "httpTimeoutMs",
        "httpResponseMapping",
        "httpCredentialId",
        "httpExpectStatus",
        "dependsOn",
        "pinnedOutputs",
      ],
      fieldDescriptions: {
        id: "string - Identificador único del paso",
        type: "literal 'http'",
        label: "string - Título legible del paso",
        httpUrl: "string - URL destino con soporte de interpolación {{ $inputs.url }}",
        httpMethod: "GET | POST | PUT | PATCH | DELETE (default: 'GET')",
        httpHeaders: "Record<string, string> - Headers HTTP manuales",
        httpBody: "unknown - Body de la petición (JSON u objeto con interpolación)",
        httpTimeoutMs: "number - Timeout en milisegundos (default: 10000ms)",
        httpResponseMapping: "Record<string, string> - Mapeo JSONPath de la respuesta a salidas (ej: { userId: '$.data.id' })",
        httpCredentialId: "string - ID opcional de credencial guardada en CredentialStore (bearer/basic/api-key)",
        httpExpectStatus: "Array<number> - Códigos de estado HTTP esperados para éxito (ej: [200, 201])",
        dependsOn: "Array<string> - Dependencias de precedencia",
      },
    },
    variables: {
      type: "variables",
      description: "Gestiona estado y variables de workflow persistentes que sobreviven a múltiples ejecuciones (cross-run).",
      requiredFields: ["id", "type", "label", "variableOps"],
      optionalFields: ["dependsOn", "pinnedOutputs"],
      fieldDescriptions: {
        id: "string - Identificador único del paso",
        type: "literal 'variables'",
        label: "string - Título legible",
        variableOps: "Array<{ op: 'get' | 'set' | 'delete' | 'increment', key: string, value?: unknown, amount?: number }> - Lista de operaciones de variables a ejecutar",
        dependsOn: "Array<string> - Dependencias de precedencia",
      },
    },
    webhook: {
      type: "webhook",
      description: "Trigger de entrada que captura peticiones HTTP entrantes (body, headers, query) desde sistemas externos.",
      requiredFields: ["id", "type", "label"],
      optionalFields: ["webhookId", "webhookSecret", "webhookResponseMode", "dependsOn", "pinnedOutputs"],
      fieldDescriptions: {
        id: "string - Identificador único del paso",
        type: "literal 'webhook'",
        label: "string - Título legible",
        webhookId: "string - ID único opcional para la URL del webhook (/api/webhooks/:webhookId)",
        webhookSecret: "string - Secreto o token opcional para validar la autenticación o firma de la petición HTTP",
        webhookResponseMode: "onReceived | onWorkflowCompleted - Modo de respuesta HTTP (inmediato 202 u síncrono al terminar)",
        dependsOn: "Array<string> - Dependencias de precedencia",
      },
    },
    delay: {
      type: "delay",
      description: "Pausa en milisegundos antes de continuar con los siguientes pasos.",
      requiredFields: ["id", "type", "label", "durationMs"],
      optionalFields: ["dependsOn", "pinnedOutputs"],
      fieldDescriptions: {
        id: "string - Identificador único del paso",
        type: "literal 'delay'",
        label: "string - Título legible",
        durationMs: "number - Duración del delay en milisegundos (mín: 1, máx: 900000 / 15 min)",
        dependsOn: "Array<string> - Dependencias de precedencia",
      },
    },
    workflow: {
      type: "workflow",
      description: "Ejecuta otro workflow como un sub-paso modular y captura sus salidas.",
      requiredFields: ["id", "type", "label", "subWorkflowId"],
      optionalFields: ["subWorkflowInputs", "dependsOn", "pinnedOutputs"],
      fieldDescriptions: {
        id: "string - Identificador único del paso",
        type: "literal 'workflow'",
        label: "string - Título legible",
        subWorkflowId: "string - ID del workflow hijo a invocar",
        subWorkflowInputs: "Record<string, unknown> - Inputs a pasar al workflow hijo",
        dependsOn: "Array<string> - Dependencias de precedencia",
      },
    },
    llm: {
      type: "llm",
      description: "Realiza una llamada directa a un modelo de lenguaje (LLM) sin herramientas ni agente autónomo.",
      requiredFields: ["id", "type", "label", "llmPrompt"],
      optionalFields: [
        "llmSystemPrompt",
        "llmModelId",
        "llmTemperature",
        "llmMaxTokens",
        "llmResponseFormat",
        "captureOutputs",
        "dependsOn",
        "pinnedOutputs",
        "timeoutMs",
        "onError",
        "retryCount",
        "retryDelayMs",
        "errorBranch",
      ],
      fieldDescriptions: {
        id: "string - Identificador único del paso",
        type: "literal 'llm'",
        label: "string - Título legible",
        llmPrompt: "string - Template del prompt usuario con interpolación {{$inputs.x}} o {{$steps.y.outputs.z}}",
        llmSystemPrompt: "string - System prompt opcional",
        llmModelId: "string - ID del modelo a utilizar",
        llmTemperature: "number - Temperatura entre 0 y 2",
        llmMaxTokens: "number - Límite de tokens de la respuesta",
        llmResponseFormat: "'text' | 'json' - Formato de la respuesta ('json' parsea automáticamente la salida a objeto)",
        dependsOn: "Array<string> - Dependencias de precedencia",
      },
    },
  },
};
