import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    tabLaboratory: "Laboratory",
    tabChat: "Chat",
    tabFiles: "Files",
    tabPreview: "Preview",
    tabOrgChart: "Org Chart",
    tabBenchmark: "Benchmark",
    tabHistory: "History",
    tabDelegations: "Delegations",
    tabTimeline: "Timeline",
    breadProyectos: "Projects",
    breadAgentes: "Agents",
    breadCanales: "Channels",
    breadTeams: "Teams",
    breadFactory: "Spaces",
    breadSettings: "Settings",
    breadSkills: "Skills",
    breadLogs: "Logs",
    breadSessions: "Sessions",
    breadAnalytics: "Analytics",
    breadMcps: "MCP Marketplace",
    btnBack: "Back",
    btnNewSession: "New Session",
    btnToggleMenu: "Toggle Menu",
    btnSessions: "Sessions",
    titleSessions: "View sessions",
  },
  es: {
    tabLaboratory: "Laboratorio",
    tabChat: "Chat",
    tabFiles: "Archivos",
    tabPreview: "Preview",
    tabOrgChart: "Org Chart",
    tabBenchmark: "Benchmark",
    tabHistory: "Historial",
    tabDelegations: "Delegaciones",
    tabTimeline: "Timeline",
    breadProyectos: "Proyectos",
    breadAgentes: "Agentes",
    breadCanales: "Canales",
    breadTeams: "Equipos",
    breadFactory: "Spaces",
    breadSettings: "Settings",
    breadSkills: "Skills",
    breadLogs: "Logs",
    breadSessions: "Sesiones",
    breadAnalytics: "Analíticas",
    breadMcps: "MCP Marketplace",
    btnBack: "Atrás",
    btnNewSession: "Nueva sesión",
    btnToggleMenu: "Menú",
    btnSessions: "Sesiones",
    titleSessions: "Ver sesiones",
  },
};
