import type { SupportedLocale } from "@/lib/types";

export const literals = {
  en: {
    title: "Project Settings",
    projectNameLabel: "Project Name",
    cloneUrlLabel: "Git Clone URL",
    cloneUrlPlaceholder: "https://github.com/user/repo.git",
    avatarUrlLabel: "Avatar URL",
    avatarUrlPlaceholder: "https://example.com/avatar.png",
    copyId: "Copy ID",
    copied: "Copied!",
    createdAtLabel: "Created At",
    diskPathLabel: "Local Disk Path",
    cancel: "Cancel",
    saveChanges: "Save Changes",
    saving: "Saving...",
    noValue: "N/A",
    updateError: "Failed to update project data.",
    deleteProject: "Danger Zone",
    deleteProjectDescription: "This action is permanent and cannot be undone. All workspace files and database state for this project will be deleted.",
    deleteConfirmLabel: "Type the project name '{name}' to confirm:",
    deleteButton: "Delete Project",
    deleting: "Deleting...",
  },
  es: {
    title: "Configuración del Proyecto",
    projectNameLabel: "Nombre del Proyecto",
    cloneUrlLabel: "URL de Git Clone",
    cloneUrlPlaceholder: "https://github.com/usuario/repo.git",
    avatarUrlLabel: "URL del Avatar",
    avatarUrlPlaceholder: "https://ejemplo.com/avatar.png",
    copyId: "Copiar ID",
    copied: "¡Copiado!",
    createdAtLabel: "Creado el",
    diskPathLabel: "Ruta local en disco",
    cancel: "Cancelar",
    saveChanges: "Guardar Cambios",
    saving: "Guardando...",
    noValue: "N/A",
    updateError: "Error al actualizar los datos del proyecto.",
    deleteProject: "Zona de Peligro",
    deleteProjectDescription: "Esta acción es permanente y no se puede deshacer. Se eliminarán todos los archivos del espacio de trabajo y el estado del proyecto.",
    deleteConfirmLabel: "Escribe el nombre del proyecto '{name}' para confirmar:",
    deleteButton: "Eliminar Proyecto",
    deleting: "Eliminando...",
  }
} satisfies Record<SupportedLocale, Record<string, string>>;
