import { join } from "node:path";
import { sessionManager } from "../session-manager";
import { broadcastToSession } from "../../ws/handler";
import { streamSimple } from "../../ai/vendor/ai/src/compat.ts";
import { TaskStateManager } from "./task-state-manager";

export interface DecomposeTasksOptions {
  username: string;
  parentSessionId: string;
}

function buildDecomposePrompt(objective: string, context: string, maxTasks: number, mode: string): string {
  const modeInstruction =
    mode === "dag"
      ? "Where possible, express parallelism by specifying which tasks each step depends on using their IDs."
      : "Tasks must be strictly sequential — each depends on the previous one completing first.";

  return [
    `Objective: "${objective}"`,
    context ? `\nAdditional context:\n${context}` : "",
    ``,
    `Decompose this objective into a structured task list of at most ${maxTasks} tasks. ${modeInstruction}`,
    ``,
    `CRITICAL: Your response must end with ONLY a valid JSON array wrapped in a \`\`\`json block. No prose after the JSON block.`,
    ``,
    "Format:",
    "```json",
    "[",
    `  {`,
    `    "id": "t1",`,
    `    "title": "Short, action-oriented title",`,
    `    "prompt": "Complete, self-contained instructions for this task. Include file paths, tools, requirements, and acceptance criteria.",`,
    `    "depends_on": [],`,
    `    "estimated_steps": 3`,
    `  }`,
    `]`,
    "```",
    ``,
    `Rules:`,
    `- IDs must be "t1", "t2", etc.`,
    `- For linear mode: each task's depends_on should contain the ID of the previous task (except the first).`,
    `- "prompt" must be fully self-contained.`,
    `- Output ONLY the JSON block.`,
  ].join("\n");
}

function parseTasksFromText(text: string): unknown | null {
  const jsonMatch = text.match(/```json\s*([\s\S]*?)\s*```/);
  if (jsonMatch) {
    try {
      return JSON.parse(jsonMatch[1].trim());
    } catch { }
  }
  const trimmed = text.trim();
  if (trimmed.startsWith("[") || trimmed.startsWith("{")) {
    try {
      return JSON.parse(trimmed);
    } catch { }
  }
  return null;
}

export function createDecomposeTasksTool(opts: DecomposeTasksOptions) {
  const { username, parentSessionId } = opts;

  return {
    name: "decompose_tasks",
    description: `Register a structured task plan with dependency tracking.
Use this when you split a complex objective into sequential or parallel steps.
You must generate the task plan details first, then call this tool to establish it.
Once the plan is registered, execute each task in order using your available tools.`,
    parameters: {
      type: "object",
      properties: {
        objective: {
          type: "string",
          description: "The high-level goal to achieve.",
        },
        tasks: {
          type: "array",
          description: "Structured task list generated by the agent.",
          items: {
            type: "object",
            properties: {
              id: {
                type: "string",
                description: "Unique task ID (e.g. 't1', 't2').",
              },
              title: {
                type: "string",
                description: "Short descriptive title.",
              },
              prompt: {
                type: "string",
                description: "Complete, self-contained instructions for this task.",
              },
              depends_on: {
                type: "array",
                items: { type: "string" },
                description: "IDs of tasks that must complete before this one starts.",
              },
              estimated_steps: {
                type: "number",
                description: "Estimated number of steps to complete.",
              },
            },
            required: ["id", "title", "prompt"],
          },
        },
      },
      required: ["objective", "tasks"],
    },
    execute: async (toolCallId: string, args: any, _parentSignal?: AbortSignal) => {
      const objective: string = args.objective || "";
      const rawTasks = args.tasks;

      if (!objective.trim()) {
        return {
          content: [{ type: "text", text: "Error: objective is required." }],
          isError: true,
        };
      }

      if (!Array.isArray(rawTasks) || rawTasks.length === 0) {
        return {
          content: [{ type: "text", text: "Error: tasks array is required and must not be empty." }],
          isError: true,
        };
      }

      const userDir = sessionManager.userConfig.ensureUserDir(username);
      const sessionDir = join(userDir, "sessions", parentSessionId);

      const oldState = TaskStateManager.getTaskState(sessionDir);
      if (oldState && oldState.status === "running") {
        return {
          content: [
            {
              type: "text",
              text: "Error: There is already an active task plan in progress. Please complete or pause the current task list before starting a new one.",
            },
          ],
          isError: true,
        };
      }

      const tasks = TaskStateManager.validateAndParseTasks(rawTasks);
      if (!tasks || tasks.length === 0) {
        return {
          content: [
            {
              type: "text",
              text: "Could not parse or validate the task list. Ensure there are no circular dependencies and all required fields are present.",
            },
          ],
          isError: true,
        };
      }

      const finalState = {
        objective,
        tasks,
        currentTaskId: tasks[0]?.id || null,
        status: "running" as const,
      };

      TaskStateManager.saveTaskState(sessionDir, finalState);

      try {
        broadcastToSession(parentSessionId, {
          type: "tasks_update",
          state: finalState,
        });
      } catch (e) {
        console.error("Failed to broadcast tasks_update:", e);
      }

      const summary = tasks
        .map((t, i) => {
          const deps = t.depends_on.length > 0 ? ` (after: ${t.depends_on.join(", ")})` : "";
          const steps = t.estimated_steps ? ` ~${t.estimated_steps} steps` : "";
          return `${i + 1}. [${t.id}] ${t.title}${deps}${steps}`;
        })
        .join("\n");

      const resultText = [
        `Registered task plan with ${tasks.length} tasks for objective: "${objective.slice(0, 80)}${objective.length > 80 ? "..." : ""}"`,
        "",
        summary,
        "",
        "Beginning execution now — working through each task in order.",
      ].join("\n");

      return {
        content: [{ type: "text", text: resultText }],
        details: {
          objective,
          tasks,
          totalTasks: tasks.length,
        },
      };
    },
  };
}

