import type { SupportedLocale } from "@/lib/types";

export const literals = {
  en: {
    title: "Team Settings",
    tabGeneral: "General",
    name: "Team Name",
    description: "Description",
    avatarUrlLabel: "Avatar/Image URL (Optional)",
    avatarUrlPlaceholder: "e.g. https://example.com/avatar.png",
    maxRounds: "Max Debate Rounds (MAX_ROUNDS)",
    showThinking: "Show Thinking (Reasoning tokens)",
    showTools: "Show Tool Calls",
    streamingEnabled: "Enable Message Streaming (Real-time output)",
    none: "None / Disabled",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving...",
    updateError: "Failed to update team settings",
    teamType: "Team Type",
    teamTypeImmutable: "The team type is fixed after creation.",
    orchestrationDesc: "Orchestration (Leader-Specialist): The leader coordinates work and delegates specific tasks to members.",
    deleteTeam: "Danger Zone",
    deleteTeamDescription: "This action is permanent and cannot be undone. All conversation history and team configurations will be deleted.",
    deleteConfirmLabel: "Type the team name '{name}' to confirm:",
    deleteButton: "Delete Team",
    deleting: "Deleting...",
  },
  es: {
    title: "Ajustes del Equipo",
    tabGeneral: "General",
    name: "Nombre del Equipo",
    description: "Descripción",
    avatarUrlLabel: "URL del Avatar/Imagen (Opcional)",
    avatarUrlPlaceholder: "ej. https://ejemplo.com/avatar.png",
    maxRounds: "Límite de Rondas de Debate (MAX_ROUNDS)",
    showThinking: "Mostrar Pensamiento (Reasoning tokens)",
    showTools: "Mostrar Ejecución de Herramientas",
    streamingEnabled: "Activar Transmisión en Tiempo Real (Streaming)",
    none: "Ninguno / Desactivado",
    cancel: "Cancelar",
    save: "Guardar",
    saving: "Guardando...",
    updateError: "Error al actualizar ajustes del equipo",
    teamType: "Tipo de Equipo",
    teamTypeImmutable: "El tipo de equipo queda fijado al crearlo.",
    orchestrationDesc: "Orquestación (Líder-Especialista): El líder coordina el trabajo y delega tareas específicas a los miembros.",
    deleteTeam: "Zona de Peligro",
    deleteTeamDescription: "Esta acción es permanente y no se puede deshacer. Se eliminarán todas las conversaciones y configuraciones del equipo.",
    deleteConfirmLabel: "Escribe el nombre del equipo '{name}' para confirmar:",
    deleteButton: "Eliminar Equipo",
    deleting: "Eliminando...",
  },
} satisfies Record<SupportedLocale, Record<string, string>>;
