import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    connected: "Connected",
    connecting: "Connecting...",
    error: "Error",
    disconnected: "Disconnected",
    noDescription: "No description available.",
    discoveredTools: "Discovered tools",
    errorDetail: "Error detail:",
    install: "Install",
    active: "Active",
    validate: "Validate",
    validateTooltip: "Hot validate tools (JSON-RPC ping)",
    disconnect: "Disconnect",
    connect: "Connect",
    editTooltip: "Edit configuration",
    deleteTooltip: "Delete server",
    builtin: "Built-in",
    tools: "tools",
  },
  es: {
    connected: "Conectado",
    connecting: "Conectando...",
    error: "Error",
    disconnected: "Desconectado",
    noDescription: "Sin descripción disponible.",
    discoveredTools: "Herramientas descubiertas",
    errorDetail: "Detalle del error:",
    install: "Instalar",
    active: "Activo",
    validate: "Validar",
    validateTooltip: "Validar herramientas en caliente (ping JSON-RPC)",
    disconnect: "Desconectar",
    connect: "Conectar",
    editTooltip: "Editar configuración",
    deleteTooltip: "Eliminar servidor",
    builtin: "Integrado",
    tools: "herramientas",
  },
};
