import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    navSkills: "Skills Library",
    navSettings: "Settings",
    navLogs: "Log Console",
    navMcps: "MCP Marketplace",
    navPlugins: "Plugins",
    navAnalytics: "Analytics",
    globalWorkspace: "Global workspace",
    manageProjects: "Manage Projects",
    manageAgents: "Manage Agents",
    manageChannels: "Manage Channels",
    factory: "Spaces",
    loading: "Loading...",
    noProjects: "No projects",
    noAgents: "No agents",
    noChannels: "No channels",
    noTeams: "No teams",
    sectionProjects: "Projects",
    sectionAgents: "Agents",
    sectionChannels: "Channels",
    sectionTeams: "Teams",
    manageTeams: "Manage Teams",
  },
  es: {
    navSkills: "Skills Library",
    navSettings: "Configuracion",
    navLogs: "Consola de Logs",
    navMcps: "MCP Marketplace",
    navPlugins: "Plugins",
    navAnalytics: "Analíticas",
    globalWorkspace: "Workspace global",
    manageProjects: "Gestionar Proyectos",
    manageAgents: "Gestionar Agentes",
    manageChannels: "Gestionar Canales",
    manageTeams: "Gestionar Equipos",
    factory: "Spaces",
    loading: "Cargando...",
    noProjects: "Sin proyectos",
    noAgents: "Sin agentes",
    noChannels: "Sin canales",
    noTeams: "Sin equipos",
    sectionProjects: "Proyectos",
    sectionAgents: "Agentes",
    sectionChannels: "Canales",
    sectionTeams: "Equipos",
  },
};
